<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.1.0924</Version>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="SQLitePCLRaw.lib.e_sqlite3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DlnaServer.Core\DlnaServer.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DlnaServer.UnitTests" />
  </ItemGroup>

</Project>
