// <auto-generated />
using System;
using DlnaServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DlnaServer.Persistence.Migrations
{
    [DbContext(typeof(DlnaDbContext))]
    [Migration("20260915173846_AddUploadDevices")]
    partial class AddUploadDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("DlnaServer.Persistence.Entities.AudioStreamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long?>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Channels")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("SampleRate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Language");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("MediaFileId", "StreamIndex")
                        .IsUnique();

                    b.ToTable("AudioStreams", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaDirectoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("Depth")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSourceRoot")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int?>("ParentDirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FullPath")
                        .IsUnique();

                    b.HasIndex("IsSourceRoot");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ParentDirectoryId", "CreatedUtc");

                    b.HasIndex("ParentDirectoryId", "Name");

                    b.ToTable("Directories", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaFileEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ContentStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DirectoryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DlnaProfileName")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Extension")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTime>("FileCreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("FileModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<string>("FullPath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsExcludedFromCache")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsMetadataSuppressed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsThumbnailRebuildForced")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsThumbnailSuppressed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MetadataFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MetadataStamp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("Mime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ThumbnailFailureCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ThumbnailStamp")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<int>("UpnpClass")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CreatedUtc");

                    b.HasIndex("FullPath")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("DirectoryId", "FileCreatedUtc");

                    b.HasIndex("DirectoryId", "Title");

                    b.ToTable("Files", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaFileTagEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(8192)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("MediaFileTags", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.ServerInstanceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastStartedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("MachineName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MachineName")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("ServerInstances", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.SubtitleStreamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExternalFilePath")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Language")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("StreamIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Language");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("MediaFileId", "StreamIndex")
                        .IsUnique();

                    b.ToTable("SubtitleStreams", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.ThumbnailContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Data")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("ThumbnailId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.HasIndex("ThumbnailId")
                        .IsUnique();

                    b.ToTable("ThumbnailContents", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.ThumbnailEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Mime")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("SizeInBytes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("FilePath")
                        .IsUnique();

                    b.HasIndex("MediaFileId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("Thumbnails", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.UploadDeviceEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AcceptLanguage")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Fingerprint")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastDestination")
                        .IsRequired()
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastUploadUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteAddress")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<int>("UploadCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserAgent")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Fingerprint")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("UploadDevices", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.VideoStreamEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AspectRatio")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long?>("Bitrate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Codec")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan?>("Duration")
                        .HasColumnType("TEXT");

                    b.Property<double?>("FrameRate")
                        .HasColumnType("REAL");

                    b.Property<int?>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MediaFileId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ModifiedUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("PixelFormat")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PublicId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rotation")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("MediaFileId")
                        .IsUnique();

                    b.HasIndex("PublicId")
                        .IsUnique();

                    b.ToTable("VideoStreams", (string)null);
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.AudioStreamEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.MediaFileEntity", "MediaFile")
                        .WithMany("AudioStreams")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaDirectoryEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.MediaDirectoryEntity", "ParentDirectory")
                        .WithMany("Subdirectories")
                        .HasForeignKey("ParentDirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ParentDirectory");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaFileEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.MediaDirectoryEntity", "Directory")
                        .WithMany("Files")
                        .HasForeignKey("DirectoryId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Directory");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaFileTagEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.MediaFileEntity", null)
                        .WithMany()
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.SubtitleStreamEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.MediaFileEntity", "MediaFile")
                        .WithMany("Subtitles")
                        .HasForeignKey("MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.ThumbnailContentEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.ThumbnailEntity", "Thumbnail")
                        .WithOne("Content")
                        .HasForeignKey("DlnaServer.Persistence.Entities.ThumbnailContentEntity", "ThumbnailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thumbnail");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.ThumbnailEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.MediaFileEntity", "MediaFile")
                        .WithOne("Thumbnail")
                        .HasForeignKey("DlnaServer.Persistence.Entities.ThumbnailEntity", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.VideoStreamEntity", b =>
                {
                    b.HasOne("DlnaServer.Persistence.Entities.MediaFileEntity", "MediaFile")
                        .WithOne("Video")
                        .HasForeignKey("DlnaServer.Persistence.Entities.VideoStreamEntity", "MediaFileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MediaFile");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaDirectoryEntity", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Subdirectories");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.MediaFileEntity", b =>
                {
                    b.Navigation("AudioStreams");

                    b.Navigation("Subtitles");

                    b.Navigation("Thumbnail");

                    b.Navigation("Video");
                });

            modelBuilder.Entity("DlnaServer.Persistence.Entities.ThumbnailEntity", b =>
                {
                    b.Navigation("Content");
                });
#pragma warning restore 612, 618
        }
    }
}
