<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <AddRazorSupportForMvc>true</AddRazorSupportForMvc>
  </PropertyGroup>

  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DlnaServer.Core\DlnaServer.Core.csproj" />
    <ProjectReference Include="..\DlnaServer.Persistence\DlnaServer.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="DlnaServer.IntegrationTests" />
  </ItemGroup>

</Project>
