<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <Version>1.1.0926</Version>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="NUnit3TestAdapter" />
    <PackageReference Include="coverlet.collector">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
    <Using Include="FluentAssertions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DlnaServer.Core\DlnaServer.Core.csproj" />
    <ProjectReference Include="..\..\src\DlnaServer.Persistence\DlnaServer.Persistence.csproj" />
    <ProjectReference Include="..\..\src\DlnaServer.Media\DlnaServer.Media.csproj" />
    <ProjectReference Include="..\..\src\DlnaServer.Upnp\DlnaServer.Upnp.csproj" />
  </ItemGroup>

</Project>
