namespace DlnaServer.Core.Dlna
{
    /// <summary>
    /// MIME types the server can advertise and serve.
    /// </summary>
    /// <remarks>
    /// Numbered in blocks by media kind so a persisted value stays readable, and so members can be added
    /// within a block without renumbering. Values are stored in the database - never renumber an existing member.
    /// The reference implementation carried roughly 140 members, most of them formats from the 1990s that no
    /// renderer asks for; this set covers the containers actually in use plus the common modern ones.
    /// </remarks>
    public enum DlnaMime
    {
        Undefined = 0,

        // Video: 1-99
        Video3gpp = 1,
        VideoAvi = 2,
        VideoMp2T = 3,
        VideoMp4 = 4,
        VideoMpeg = 5,
        VideoOgg = 6,
        VideoQuicktime = 7,
        VideoWebm = 8,
        VideoXFlv = 9,
        VideoXMatroska = 10,
        VideoXMsAsf = 11,
        VideoXMsvideo = 12,
        VideoXMswmv = 13,

        VideoAnimaflex = 14,
        VideoAvsVideo = 15,
        VideoDl = 16,
        VideoFli = 17,
        VideoGl = 18,
        VideoMsvideo = 19,
        VideoVdo = 20,
        VideoVivo = 21,
        VideoVndRnRealvideo = 22,
        VideoVndVivo = 23,
        VideoVosaic = 24,
        VideoXAmtDemorun = 25,
        VideoXAmtShowrun = 26,
        VideoXAtomic3DFeature = 27,
        VideoXDl = 28,
        VideoXDv = 29,
        VideoXFli = 30,
        VideoXGl = 31,
        VideoXIsvideo = 32,
        VideoXMotionJpeg = 33,
        VideoXMpeg = 34,
        VideoXMpeq2A = 35,
        VideoXMsAsfPlugin = 36,
        VideoXQtc = 37,
        VideoXScm = 38,
        VideoXSgiMovie = 39,
        VideoWindowsMetafile = 40,
        VideoXglMovie = 41,

        // Audio: 100-199
        AudioAac = 100,
        AudioFlac = 101,
        AudioMp4 = 102,
        AudioMpeg = 103,
        AudioMpeg3 = 104,
        AudioOgg = 105,
        AudioWav = 106,
        AudioXAiff = 107,
        AudioXMswma = 108,
        AudioXWav = 109,

        AudioAiff = 110,
        AudioBasic = 111,
        AudioIt = 112,
        AudioMake = 113,
        AudioMid = 114,
        AudioMidi = 115,
        AudioMod = 116,
        AudioNspaudio = 117,
        AudioS3M = 118,
        AudioTspAudio = 119,
        AudioTsplayer = 120,
        AudioVndQcelp = 121,
        AudioVoc = 122,
        AudioVoxware = 123,
        AudioXAdpcm = 124,
        AudioXAu = 125,
        AudioXGsm = 126,
        AudioXJam = 127,
        AudioXLiveaudio = 128,
        AudioXMatroska = 129,
        AudioXMid = 130,
        AudioXMidi = 131,
        AudioXMod = 132,
        AudioXMpeg = 133,
        AudioXMpeg3 = 134,
        AudioXMpequrl = 135,
        AudioXNspaudio = 136,
        AudioXPnRealaudio = 137,
        AudioXPnRealaudioPlugin = 138,
        AudioXPsid = 139,
        AudioXRealaudio = 140,
        AudioXTwinvq = 141,
        AudioXTwinvqPlugin = 142,
        AudioXVndAudioexplosionMjuicemediafile = 143,
        AudioXVoc = 144,
        AudioXm = 145,
        AudioMusicCrescendo = 146,
        AudioXMusicXMidi = 147,

        // Image: 200-299
        ImageBmp = 200,
        ImageGif = 201,
        ImageJpeg = 202,
        ImagePng = 203,
        ImageSvgXml = 204,
        ImageTiff = 205,
        ImageWebp = 206,
        ImageXIcon = 207,

        ImageCmuRaster = 208,
        ImageFif = 209,
        ImageFlorian = 210,
        ImageG3Fax = 211,
        ImageIef = 212,
        ImageJutvision = 213,
        ImageNaplps = 214,
        ImagePict = 215,
        ImagePjpeg = 216,
        ImageVasa = 217,
        ImageVndDwg = 218,
        ImageVndFpx = 219,
        ImageVndRnRealflash = 220,
        ImageVndRnRealpix = 221,
        ImageVndWapWbmp = 222,
        ImageVndXiff = 223,
        ImageXCmuRaster = 224,
        ImageXDwg = 225,
        ImageXJg = 226,
        ImageXJps = 227,
        ImageXNiff = 228,
        ImageXPcx = 229,
        ImageXPict = 230,
        ImageXPortableAnymap = 231,
        ImageXPortableBitmap = 232,
        ImageXPortableGraymap = 233,
        ImageXPortablePixmap = 234,
        ImageXQuicktime = 235,
        ImageXRgb = 236,
        ImageXTiff = 237,
        ImageXWindowsBmp = 238,
        ImageXXbitmap = 239,
        ImageXXbm = 240,
        ImageXXpixmap = 241,
        ImageXXwd = 242,
        ImageXXwindowdump = 243,

        // Subtitle: 300-399
        SubtitleMicroDVD = 300,
        SubtitleSubrip = 301,
        SubtitleTtmlXml = 302,
        SubtitleVtt = 303,
        SubtitleXSubrip = 304,
    }
}
